# Robert Brandl
biomark = read_excel("C:\\Users\\rober\\OneDrive\\Biomark.xls")
#11.36
#a
print(summary(biomark$voplus))
print(sd(biomark$voplus))
plot(biomark$voplus, main="VO+ Scatterplot", ylab="VO+")
print(summary(biomark$vominus))
print(sd(biomark$vominus))
plot(biomark$vominus, main="VO- Scatterplot", ylab="VO-")
print(summary(biomark$oc))
print(sd(biomark$oc))
plot(biomark$oc, main="OC Scatterplot", ylab="OC")
print(summary(biomark$trap))
print(sd(biomark$trap))
plot(biomark$trap, main="TRAP Scatterplot", ylab="TRAP")
print(cor(biomark[, c('voplus', 'vominus', 'oc', 'trap')]))
#b
plot(biomark$voplus,biomark$vominus, main="Scatterplot of VO+ vs. VO-", ylab = "VO-", xlab = "VO+")
abline(reg = lm(biomark$vominus ~ biomark$voplus))
plot(biomark$voplus,biomark$oc, main="Scatterplot of VO+ vs. OC", ylab = "OC", xlab = "VO+")
abline(reg = lm(biomark$oc ~ biomark$voplus))
plot(biomark$voplus,biomark$trap, main="Scatterplot of VO+ vs. TRAP", ylab = "TRAP", xlab = "VO+")
abline(reg = lm(biomark$trap ~ biomark$voplus))
plot(biomark$vominus,biomark$oc, main="Scatterplot of VO- vs. OC", ylab = "OC", xlab = "VO-")
abline(reg = lm(biomark$oc ~ biomark$vominus))
plot(biomark$vominus,biomark$trap, main="Scatterplot of VO- vs. TRAP", ylab = "TRAP", xlab = "VO-")
abline(reg = lm(biomark$trap ~ biomark$vominus))
plot(biomark$oc,biomark$trap, main="Scatterplot of OC vs. TRAP", ylab = "TRAP", xlab = "OC")
abline(reg = lm(biomark$trap ~ biomark$oc))
#11.37
fm1 = lm(voplus ~ oc, data=biomark)
print(summary(fm1))
plot(voplus ~ oc,data=biomark,main="Linear Model Using OC to Predict VO+")
abline(fm1, col="blue",lwd=3)
boxplot(residuals(fm1),main='Boxplot: Residuals')
qqnorm(residuals(fm1), main="QQ Plot: Residuals")
fm2 = lm(voplus ~ oc + trap, data=biomark)
print(summary(fm2))
boxplot(residuals(fm2),main='Boxplot: Residuals')
qqnorm(residuals(fm2), main="QQ Plot: Residuals")
#11.38
fm3 = lm(voplus ~ oc + trap + vominus, data=biomark)
print(summary(fm3))
boxplot(residuals(fm3),main='Boxplot: Residuals')
qqnorm(residuals(fm3), main="QQ Plot: Residuals")
fm4 = lm(voplus ~ oc + vominus, data=biomark)
print(summary(fm4))
boxplot(residuals(fm4),main='Boxplot: Residuals')
qqnorm(residuals(fm4), main="QQ Plot: Residuals")
#11.39
#     from 11.36 a
print(summary(biomark$lvoplus))
print(sd(biomark$lvoplus))
plot(biomark$lvoplus, main="LVO+ Scatterplot", ylab="LVO+")
print(summary(biomark$lvominus))
print(sd(biomark$lvominus))
plot(biomark$lvominus, main="LVO- Scatterplot", ylab="LVO-")
print(summary(biomark$loc))
print(sd(biomark$loc))
plot(biomark$loc, main="LOC Scatterplot", ylab="LOC")
print(summary(biomark$ltrap))
print(sd(biomark$ltrap))
plot(biomark$ltrap, main="LTRAP Scatterplot", ylab="LTRAP")
print(cor(biomark[, c('lvoplus', 'lvominus', 'loc', 'ltrap')]))
#    b
plot(biomark$lvoplus,biomark$lvominus, main="Scatterplot of LVO+ vs. LVO-", ylab = "LVO-", xlab = "LVO+")
abline(reg = lm(biomark$lvominus ~ biomark$lvoplus))
plot(biomark$lvoplus,biomark$loc, main="Scatterplot of LVO+ vs. LOC", ylab = "LOC", xlab = "LVO+")
abline(reg = lm(biomark$loc ~ biomark$lvoplus))
plot(biomark$lvoplus,biomark$ltrap, main="Scatterplot of LVO+ vs. LTRAP", ylab = "LTRAP", xlab = "LVO+")
abline(reg = lm(biomark$ltrap ~ biomark$lvoplus))
plot(biomark$lvominus,biomark$loc, main="Scatterplot of LVO- vs. LOC", ylab = "LOC", xlab = "LVO-")
abline(reg = lm(biomark$loc ~ biomark$lvominus))
plot(biomark$lvominus,biomark$ltrap, main="Scatterplot of LVO- vs. LTRAP", ylab = "LTRAP", xlab = "LVO-")
abline(reg = lm(biomark$ltrap ~ biomark$lvominus))
plot(biomark$loc,biomark$ltrap, main="Scatterplot of LOC vs. LTRAP", ylab = "LTRAP", xlab = "LOC")
abline(reg = lm(biomark$ltrap ~ biomark$loc))
#     from 11.37
fm5 = lm(lvoplus ~ loc, data=biomark)
print(summary(fm5))
plot(lvoplus ~ loc,data=biomark,main="Linear Model Using LOC to Predict LVO+")
abline(fm5, col="blue",lwd=3)
boxplot(residuals(fm5),main='Boxplot: Residuals')
qqnorm(residuals(fm5), main="QQ Plot: Residuals")
fm6 = lm(lvoplus ~ loc + ltrap, data=biomark)
print(summary(fm6))
boxplot(residuals(fm6),main='Boxplot: Residuals')
qqnorm(residuals(fm6), main="QQ Plot: Residuals")
#     from 11.38
fm7 = lm(lvoplus ~ loc + ltrap + lvominus, data=biomark)
print(summary(fm7))
boxplot(residuals(fm7),main='Boxplot: Residuals')
qqnorm(residuals(fm7), main="QQ Plot: Residuals")
fm8 = lm(lvoplus ~ loc + lvominus, data=biomark)
print(summary(fm8))
boxplot(residuals(fm8),main='Boxplot: Residuals')
qqnorm(residuals(fm8), main="QQ Plot: Residuals")
#11.40
#     from 11.37
fm9 = lm(vominus ~ oc, data=biomark)
print(summary(fm9))
plot(vominus ~ oc,data=biomark,main="Linear Model Using OC to Predict VO-")
abline(fm9, col="blue",lwd=3)
boxplot(residuals(fm9),main='Boxplot: Residuals')
qqnorm(residuals(fm9), main="QQ Plot: Residuals")
fm10 = lm(vominus ~ oc + trap, data=biomark)
print(summary(fm10))
boxplot(residuals(fm10),main='Boxplot: Residuals')
qqnorm(residuals(fm10), main="QQ Plot: Residuals")
#      from 11.38
fm11 = lm(vominus ~ oc + trap + voplus, data=biomark)
print(summary(fm11))
boxplot(residuals(fm11),main='Boxplot: Residuals')
qqnorm(residuals(fm11), main="QQ Plot: Residuals")
fm12 = lm(vominus ~ oc + voplus, data=biomark)
print(summary(fm12))
boxplot(residuals(fm12),main='Boxplot: Residuals')
qqnorm(residuals(fm12), main="QQ Plot: Residuals")
#11.41
#     from 11.37
fm13 = lm(lvominus ~ loc, data=biomark)
print(summary(fm13))
plot(lvominus ~ loc,data=biomark,main="Linear Model Using LOC to Predict LVO-")
abline(fm13, col="blue",lwd=3)
boxplot(residuals(fm13),main='Boxplot: Residuals')
qqnorm(residuals(fm13), main="QQ Plot: Residuals")
fm14 = lm(lvominus ~ loc + ltrap, data=biomark)
print(summary(fm14))
boxplot(residuals(fm14),main='Boxplot: Residuals')
qqnorm(residuals(fm14), main="QQ Plot: Residuals")
#      from 11.38
fm15 = lm(lvominus ~ loc + ltrap + lvoplus, data=biomark)
print(summary(fm15))
boxplot(residuals(fm15),main='Boxplot: Residuals')
qqnorm(residuals(fm15), main="QQ Plot: Residuals")
fm16 = lm(lvominus ~ loc + lvoplus, data=biomark)
print(summary(fm16))
boxplot(residuals(fm16),main='Boxplot: Residuals')
qqnorm(residuals(fm16), main="QQ Plot: Residuals")